//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_H1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naimenovanie
    {
        public int id { get; set; }
        public string Articul { get; set; }
        public string Naimenovanie1 { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
